const SEARCH_USERS = 'SEARCH_USERS';
const GET_USER = 'GET_USER';
const CLEAR_USERS = 'CLEAR_USERS';
const GET_REPOS = 'GET_REPOS';
const SET_LOADING = 'SET_LOADING';
const SET_ALERT = 'SET_ALERT';
const REMOVE_ALERT = 'REMOVE-ALERT';

export { SEARCH_USERS, GET_USER, CLEAR_USERS, GET_REPOS, REMOVE_ALERT, SET_ALERT, SET_LOADING };
